# Generated by Django 4.1 on 2022-08-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='sistema',
        ),
        migrations.AddField(
            model_name='archivo',
            name='sistemas',
            field=models.ManyToManyField(to='content.sistema'),
        ),
    ]
