# Generated by Django 4.1 on 2022-08-28 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sistema_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Api Key'),
        ),
    ]
