# Generated by Django 4.1 on 2022-08-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_sistema_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='validar_api_key',
            field=models.BooleanField(default=True, verbose_name='Validar API Key'),
        ),
    ]
