# Generated by Django 4.1 on 2022-08-28 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_archivo_validar_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='api_key',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='Api Key'),
        ),
    ]
